### ISSUE TITLE
Makefile is attempting to access a non-existent folder

### ISSUE THREAD

**Issue by spsquared** [ev3rt-git/ev3rt-hrp3#2]
I have followed all of the documentation on installing and setting up.

However, upon entering the sdk/workspace and run the command `make app=helloev3`, the following error occurs:

`C:\Ruby26-x64\bin\ruby.exe: No such file or directory -- /home/[user]/ev3rt-git/ev3rt-hrp3/sdk/workspace/../../configure.rb (LoadError)
make: *** [../common/Makefile.workspace:152: prepare-obj-folder] Error 1`

I have installed ruby and added it to path. I have run the initiation and update commands.
I have reinstalled Cygwin and re-cloned the repository. This does not seem to be a problem with other people, however.
Upon attempting to enter the folder on the windows platform, I discover that `/home/[user]/ev3rt-git/ev3rt-hrp3/sdk/workspace/../../configure.rb` does not even exist.

Am I doing something wrong? I have reviewed the documentation multiple times.
The same problem occurs in [ev3rt-hrp2](https://github.com/ev3rt-git/ev3rt-hrp2).

(edited)

**Comment by YixiaoLi** [comment]
It seems that you are using Ruby for Windows (`C:\Ruby26-x64\bin\ruby.exe`) rather than Ruby package provided by Cygwin.
Ruby for Windows does not support Cygwin's UNIX-style path. 
Could you try to install Ruby using Cygwin Setup (setup-x86.exe or setup-x86_64.exe)?

**Comment by spsquared** [comment]
I have uninstalled everything and installed everything all over again. It turned out you cannot install two things at once. This will cause it to not recognize things. That is a simple issue that can be avoided, though.
